version: '2.3'

services:
  main:
    container_name: sea-story-vcd
    build:
      context: ./
      dockerfile: Dockerfile
    runtime: nvidia
    restart: always
    volumes:
      - type: volume
        source: nfs_shared_
        target: /mldisk/nfs_shared_
        volume:
          nocopy: true
      - type: volume
        source: nfs_shared
        target: /mlsun/nfs_shared
        volume:
          nocopy: true
      - "/media/mmlab/hdd:/hdd"
    ports:
      - "18070:22"
      - "18071:6006"
    ipc: host
    stdin_open: true
    tty: true

volumes:
  nfs_shared:
    driver_opts:
      type: "nfs"
      o: "addr=mlsun.sogang.ac.kr,nolock,soft,rw"
      device: ":/volume1/nfs_shared"
  nfs_shared_:
    driver_opts:
      type: "nfs"
      o: "addr=mldisk.sogang.ac.kr,nolock,soft,rw"
      device: ":/volume2/nfs_shared_"
